# version: '3'  #choose version as per your need

# services:
#   cassandra:
#     image: cassandra:latest
#     container_name: cassandra-container
#     ports:
#       - "9042:9042"
#     environment:
#       - CASSANDRA_USER=admin
#       - CASSANDRA_PASSWORD=admin
#     volumes:
#       - cassandra-data:/var/lib/cassandra
#       - ./db-schema:/docker-entrypoint-initdb.d/

# volumes:
#   cassandra-data:

version: '3'

services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
    networks:
      - cassandra-network
  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2
    networks:
      - cassandra-network
  # cassandra3:
  #   image: cassandra:latest
  #   container_name: cassandra3
  #   environment:
  #     - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
  #   networks:
  #     - cassandra-network

  # migrate:
  #   image: jmiranda0521/cassandra:2.5
  #   environment:
  #     - USER=cassandra
  #     - PASSWORD=cassandra
  #     - KEYSPACE=loggerdb
  #     - MODE=prod
  #   networks:
  #     - cassandra-network    

networks:
  cassandra-network:
    # driver: bridge​  